config/routes.rb
Rails.application.routes.draw do
  get 'movies/redirect'
  devise_for :users
  root to: 'pages#home'
  resources :movies, only: [:show, :create, :index]
  get '/movies/:id/redirect', to:'movies#redirect', as: 'redirect'
  resources :criteria, only: [:edit, :create, :update]
  post '/vues', to: 'vues#create', as: 'vue'
  post '/vues/watch', to: 'vues#watch', as: 'watch'
  get '/vues', to: 'vues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @movie = Movie.find(params[:id])
    @vue = Vue.new
  end

  def create
  end

  def index
    @vues = current_user.vues.where(conjoint1: true).or(current_user.vues.where(conjoint2: true))
    @couple = @vues.select { |v| v.conjoint1 || v.conjoint2 }
    @conjoint1 = @vues.select { |v| v.conjoint1 }
    @conjoint2 = @vues.select { |v| v.conjoint2 }
  end

  def redirect
  end
end

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/redirect.html.erb
<h1>Movies#redirect</h1>
<p>Find me in app/views/movies/redirect.html.erb</p>

app/views/movies/show.html.erb
<% content_for(:body_style) { "background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(#{@movie.photo_url}); background-size: cover; background-position: 50% 25%;"} %>
  <div class="movie-ctn">
    <div class="responsive">
          <%= image_tag @movie.photo_url, alt: @movie.title %>
    </div>

    <div class="sans-interet">
      <div class="movie-dcp">
        <div class="movie-title">
          <h1> <%= @movie.title %> </h1>
          <div class="desc">
            <h4> (<%= @movie.date.first(4) %>) </h4>
          </div>
        </div>

        <div class="desc">
          <p><strong> Synopsis :</strong> <%= @movie.synopsis %> </p>
        </div>

        <div class="desc">
          <p> <strong>Actors :</strong>  <% actor_list = "" %>
            <% @movie.cast.each do |actor| %>
              <% actor_list << "#{actor}," + " " %>
            <% end %>
            <%= actor_list[0...-2] %>
          </p>
        </div>

         <div class="desc">
          <p><strong> Director : </strong><%= @movie.director %> </p>
        </div>

        <div class="desc">
          <p><strong> Duration :</strong> <%= @movie.duration %>min </p>
        </div>

        <div class="desc_logo">
          <div class="logoimdb">
            <p><%= image_tag "logoimbd.png", alt: "alttext" %> <strong>Rating :</strong> <%= @movie.rating %></p>
          </div>
        </div>
      </div>

    <div class="movie-btn">
      <% translate_platform(current_user.criterium.platforms).each do |platform| %>
        <% @movie.urls.select do |link| %>
          <% if link.include?(platform) %>
            <%= simple_form_for @vue, url: watch_path, method: 'post' do |f| %>
              <%= hidden_field_tag(:movie_id, @movie.id) %>
              <%= hidden_field_tag(:link, link) %>
              <%= f.input :conjoint1, input_html: { checked: true }, as: :hidden %>
              <%= f.input :conjoint2, input_html: { checked: true }, as: :hidden %>
              <%= f.button :submit, "Watch on #{platform}" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
     </div>

    <p id="barre"></p>

    <div class="criteria-selection">
      <p><strong> Your selection criteria : </strong> </p>
      <% if current_user.criterium.duration == 105 %>
        <p id="duration" > <%= "Runtime < 1h45" %> </p>
      <% end %>
      <% if current_user.criterium.duration == 150 %>
       <p id="duration"> <%= "Runtime < 2h30" %> </p>
      <% end %>
      <% if current_user.criterium.duration == 500 %>
        <p id="duration"> <%= "Runtime > 3h" %> </p>
      <% end %>

      <% if current_user.criterium.rating == 4 %>
        <p id="rating" > <%= "Any movie" %> </p>
      <% end %>
      <% if current_user.criterium.rating == 6 %>
       <p id="rating"> <%= "Mainstream" %> </p>
      <% end %>
      <% if current_user.criterium.rating == 8 %>
        <p id="rating"> <%= "Masterpiece" %> </p>
      <% end %>
    </div>

    <div class="btn-conjoint">
      <%= simple_form_for @vue, url: vue_path, method: 'post' do |f| %>
        <%= hidden_field_tag(:movie_id, @movie.id) %>
        <%= f.input :conjoint1, input_html: { checked: true }, as: :hidden %>
        <%= f.button :submit, "#{current_user.conjoint1} has seen it" %>
      <% end %>

      <%= simple_form_for @vue, url: vue_path, method: 'post' do |f| %>
        <%= hidden_field_tag(:movie_id, @movie.id) %>
        <%= f.input :conjoint2, input_html: { checked: true }, as: :hidden %>
        <%= f.button :submit, "#{current_user.conjoint2} has seen it" %>
      <% end %>

      <%= simple_form_for @vue, url: vue_path, method: 'post' do |f| %>
        <%= hidden_field_tag(:movie_id, @movie.id) %>
        <%= f.input :conjoint1, input_html: { checked: true }, as: :hidden %>
        <%= f.input :conjoint2, input_html: { checked: true }, as: :hidden %>
        <%= f.button :submit, "Both have seen it" %>
      <% end %>
    </div>
  </div>
</div>