config/routes.rb
Rails.application.routes.draw do
  get 'movies/redirect'
  devise_for :users
  root to: 'pages#home'
  resources :movies, only: [:show, :create, :index]
  get '/movies/:id/redirect', to:'movies#redirect', as: 'redirect'
  resources :criteria, only: [:edit, :create, :update]
  post '/vues', to: 'vues#create', as: 'vue'
  post '/vues/watch', to: 'vues#watch', as: 'watch'
  get '/vues', to: 'vues#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="first-lign">
    <div class="footer-coordonate">
      Ichooze Co. 20 Capucins's street - Lyon, France
    </div>
    <div class="symbols">
      ||
    </div>
    <div class="footer-thanks">
      Thanks for choosing with us ! You'll be back...
    </div>
  </div>
  <div class="footer-text-imdb">
    This product uses the TMDb API but is not endorsed or certified by TMDb
  <img src="https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_2-d537fb228cf3ded904ef09b136fe3fec72548ebc1fea3fbbd1ad9e36364db38b.svg" alt="the movie db" width="20" height="20">
  </div>
</div>

app/views/shared/_matrix.html.erb
<html>
  <head>
        <title>HTML5 Canvas Matrix Effect</title>

  </head>
  <body>

    <canvas id="canvas">Canvas is not supported in your browser.</canvas>
    <canvas id="canvas2">Canvas is not supported in your browser.</canvas>
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="z-index: 10;">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logoichooze1.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My library", vues_path, class: "nav-link" %>
          <% end %>
        </li>
        <% if user_signed_in? == false %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          <% end %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>